APP_NAME: SPARC
APP_VERSION: 2.0

DB_NAME: sparc2
DB_USER: sparc2
DB_PASS: sparc2

VENV_NAME: sparc2
VENV_PATH: /home/vagrant/.venvs/sparc2

STATIC_SRC: /home/vagrant/sparc2.git/sparc2/static/sparc2
STATIC_DEST: /var/www
STATIC_ROOT: /var/www/static  # Used by sparc2_webserver_static / nginx config
WWW_ROOT: /var/www

PRJ_PARENT_PATH: /home/vagrant
PRJ_REPO_NAME: sparc2.git

PRJ_REPO_PATH_MAIN: /home/vagrant/sparc2.git
PRJ_DJ_NAME: sparc2

REQS:
  - "~/sparc2.git/requirements.txt"

JENKS: "git+https://github.com/perrygeo/jenks.git#egg=jenks"

STATIC_DEV_DEPS:
  - { name: bower, version: 1.7.7 }
  - { name: gulp, version: 3.9.1 }
  - { name: del, version: 2.2.0 }
  - { name: path, version: 0.12.7 }
  - { name: jshint, version: 2.9.1 }
  - { name: gulp-concat, version: 2.6.0 }
  - { name: gulp-jshint, version: 2.0.0 }
  - { name: gulp-minify, version: 0.0.5 }
  - { name: gulp-uglify, version: 1.5.2 }
  - { name: gulp-rename, version: 1.2.2 }
  - { name: gulp-less, version: 3.0.5 }

COMMON_EDITABLE_PACKAGES:  # For role "common_editable"
  - name: sparc2
    parent: /home/vagrant
    path: sparc2.git
  - name: geosite-framework-django
    parent: /home/vagrant
    path: geosite-framework-django.git


# Added to pg_hba.conf in sparc2_db role
PATH_PG_HBA: "/etc/postgresql/9.3/main/pg_hba.conf"
PATH_PG_CONF: "/etc/postgresql/9.3/main/postgresql.conf"

DATABASE_ACL:
  - "local {{ DB_NAME }} {{ DB_USER }} md5"
  - "host {{ DB_NAME }} {{ DB_USER }} 127.0.0.1/32 md5"
  - "host {{ DB_NAME }} {{ DB_USER }} 10.0.2.2/32 md5"

DATABASE_LISTEN_ADDRESSES:
  - "*"
