---

- name: Create a SPARC virtual machine via vagrant
  hosts: all
  remote_user: vagrant
  roles:
    - common_editable  # Installs local sparc2.git and geosite-framework.git repos as editable
    - common_gdal
