---
#  Suppress output with suffix > /dev/null 2>&1

#- name: "GDAL Python Bindings / Download"
#  shell: "/home/vagrant/.venvs/sparc2/bin/pip install --no-install GDAL==2.0.0"

#- name: "GDAL Python Bindings / Config"
#  shell: "sed -i \"s/\\.\\.\\/\\.\\.\\/apps\\/gdal-config/\\/usr\\/bin\\/gdal-config/g\" setup.cfg"
#  args:
#    chdir: "{{ VENV_PATH }}/build/GDAL"

#- name: "GDAL Python Bindings / Install"
#  shell: "{{ item }}"
#  args:
#    chdir: "{{ VENV_PATH }}/build/GDAL"
#  with_items:
#    - "/home/vagrant/.venvs/sparc2/bin/python setup.py build_ext --include-dirs=/usr/include/gdal"
#    - "/home/vagrant/.venvs/sparc2/bin/pip install --no-download GDAL==2.0.0"
